version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/angular-chat-dev
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_dev_data:/data/db
    restart: unless-stopped

volumes:
  mongo_dev_data:
